[tasks.build-musl]
command = "cargo"
args = ["build", "--target", "x86_64-unknown-linux-musl", "--release"]

[tasks.run]
command = "cargo"
args = ["run"]
env = { RUST_LOG = "info" }

[tasks.test]
command = "cargo"
args = ["test"]