app = "vrl-server"

[build]
  image = "lucperkins/vrl-server:latest"

[[services]]
  internal_port = 8080
  protocol = "TCP"

  [services.port.80]
    handlers = ["HTTP"]

  [services.port.443]
    handlers = ["TLS", "HTTP"]
