app = "vrl-server"

[build]
  image = "lucperkins/vrl-server:latest"

[[services]]
  internal_port = 8080
  protocol = "TCP"

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["http", "tls"]
    port = "443"
