[package]
name = "vrl-server"
version = "0.1.0"
edition = "2018"

[dependencies]
structopt = "0.3.23"
tokio = { version = "1.11.0", default-features = false, features = ["full"] }
vrl-server = { git = "https://github.com/vectordotdev/vector", branch = "vrl-web-server" }
