name: Build, test, deploy
on:
  push:
    branches:
      - main
    paths:
      - 'vrl-web-server-warp/Cargo.*'
      - 'vrl-web-server-warp/Dockerfile'
      - 'vrl-web-server-warp/fly.toml'
      - 'vrl-web-server-warp/setup.sh'
      - 'vrl-web-server-warp/src/**'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  test:
    name: Test Warp server
    defaults:
      working-directory: vrl-web-server-warp
    steps:
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v2
      - name: Run tests
        run: cargo make test
  docker:
    name: Build Docker image
    defaults:
      working-directory: vrl-web-server-warp
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lucperkins/vrl-server:latest
  deploy:
    name: Deploy VRL Web server
    defaults:
      working-directory: vrl-web-server-warp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        with:
          args: deploy